workspace(name = "rust_basics")

# RULES FOR GETTING EXTERNAL DEPENDENCIES #####################################

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# CONFIGURE BAZEL_SKYLIB ######################################################

# `@io_bazel_rules_rust` depends upon this starlark helper library.
http_archive(
    name = "bazel_skylib",
    url = "https://github.com/bazelbuild/bazel-skylib/releases/download/0.9.0/bazel_skylib-0.9.0.tar.gz",
    sha256 = "1dde365491125a3db70731e25658dfdd3bc5dbdfd11b840b3e987ecf043c7ca0",
)

# CONFIGURE RULES_RUST ########################################################

# Master commit as of 2019-09-19:
RULES_RUST_MASTER_COMMIT="f727669b8ac3c9d237ed9bc7833b8e1eeec90506"
RULES_RUST_MASTER_SHA256="019958e96fcb9d8b5e5f74f31ad58f9c59804e8c04cf5aae03b983001edc79e0"

http_archive(
    name = "io_bazel_rules_rust",
    sha256 = RULES_RUST_MASTER_SHA256,
    strip_prefix = "rules_rust-{}".format(RULES_RUST_MASTER_COMMIT),
    url = "https://github.com/bazelbuild/rules_rust/archive/{}.tar.gz".format(RULES_RUST_MASTER_COMMIT),
)

# Run the bazel version check that comes with `rules_rust`:
load("@io_bazel_rules_rust//:workspace.bzl", "bazel_version")
bazel_version(name = "bazel_version")

load("@io_bazel_rules_rust//rust:repositories.bzl", "rust_repositories")
rust_repositories()
